apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nameApp }}
spec:
  type: {{ .Values.ClusterIP }}
  ports:
  - port: {{ .Values.containerPort }}
    targetPort: {{ .Values.targetPort }}
    name: {{ .Values.nameApp }}
  selector:
    app: {{ .Values.nameApp }}